apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: product-ms
  name: product-ms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-ms
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: product-ms
    spec:
      containers:
      - image: southamerica-east1-docker.pkg.dev/microservices-curse-428420/image-registry/products-ms
        name: products-ms
        env:
        - name: DATABASE_URL
          value: "file:./dev.db"
        - name: NATS_SERVERS
          value: "nats://nats"
        resources: {}
status: {}
